/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.lee.gradle.plugins

import com.github.javaparser.utils.Utils.assertNotNull
import org.gradle.internal.impldep.org.junit.Test
import org.gradle.testfixtures.ProjectBuilder


/**
 * A simple unit test for the 'com.github.lee.gradle.plugins.greeting' plugin.
 */
class Gradle_pluginsPluginTest {
    @Test
    fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.github.lee.gradle.plugins.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
